# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Cam Zhou
title-normal: Harvey Mudd College
email: wzhou@hmc.edu
description: "Programmer | Designer | Photographer"
url: "https://camzhou.github.io" # the base hostname & protocol for your site
author: Cam Zhou
street_address: 340 E Foothill Blvd
city: Claremont
state: CA
zip_code: 91711
country: United States of America
phone: (909) 344-4898

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: https://500px.com/wzhou
facebook_url: https://www.facebook.com/zhoucam
github_url: https://github.com/CamZhou
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/weiyu-zhou-230b76a1
pinterest_url: 
slack_url: 
twitter_url:

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username:
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
og_image: “logo.jpg”
google_site_verification: 
